[package]
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
categories = ["game-development"]
description = "A camera that allows panning by dragging with the mouse"
edition = "2021"
keywords = ["gamedev", "bevy"]
license = "MIT OR Apache-2.0"
name = "bevy_pancam"
repository = "https://github.com/johanhelsing/bevy_pancam"
version = "0.10.0"

[features]
bevy_egui = ["dep:bevy_egui"]

[dependencies]
bevy = {version = "0.13", features = ["bevy_render"], default-features = false}
bevy_egui = {version = "0.25", optional = true, default-features = false}

[dev-dependencies]
# bevy = {version = "0.9", default-features = false, features = [
bevy = {version = "0.13", default-features = false, features = [
  "bevy_render",
  "bevy_asset",
  "bevy_sprite",
  "bevy_winit",
  "bevy_core_pipeline",
  "x11", # github actions runners don't have libxkbcommon installed, so can't use wayland
]}
# bevy-inspector-egui = {version = "0.19", default-features = false}
bevy_egui = {version = "0.25", default-features = false, features = ["default_fonts"]}
rand = "0.8"

[[example]]
name = "egui"
required-features = ["bevy_egui"]
